export const defaultMetaData = {
  description: `I am Rocky Essel, a front-end developer who is passionate about web technologies.`,
  title: `Homepage`,
  image: `https://esselr.vercel.app/homepage.png`,
  alt: 'Homepage',
  keywords: 'portfolio website,blog,website,projects',
  type: `website`,
  publishedAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  author_name: 'Rocky Essel',
  MIME: 'png',
};

  export const data = [
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
    {
      category: 'Movies',
      estimated_time: '7',
      author: 'brennan klein',
      name: 'Potential Stranger Things Season 5 Release Window Suggested By Star',
      description: `Hogwarts Legacy beautifully recreates the world of Harry Potter and fills it with quirky characters, tense combat, and a huge amount of collectibles.`,
      image: '/deadpool.png',
    },
  ];
